import type { Extraction } from "./schema";
import { db, type IncidentRow, type ReportRow } from "./db";

/**
 * Conservative duplicate detection.
 *
 * Candidates are generated by geography, time window and incident type FIRST, then
 * semantic similarity decides among them. Similarity alone is not sufficient: two
 * reports of "ghar mein pani aa gaya" from houses 15km apart are near-identical text
 * describing different emergencies, and merging them loses a household.
 *
 * Borderline matches are never merged silently. They are held as possible duplicates
 * for an operator to judge, because a wrong merge hides an emergency and a wrong
 * split only costs a second look.
 */

const EMBED_MODEL = process.env.AMANSIGNAL_EMBED_MODEL ?? "text-embedding-v4";
const BASE =
  process.env.DASHSCOPE_BASE_URL ??
  "https://dashscope-intl.aliyuncs.com/compatible-mode/v1";

/** Same emergency, reported within this window, is plausibly the same event. */
export const TIME_WINDOW_MS = 6 * 60 * 60 * 1000;
/** Rough metres per degree of latitude; good enough for a proximity gate. */
const M_PER_DEG = 111_320;
export const GEO_RADIUS_M = 500;

export const AUTO_LINK_THRESHOLD = 0.82;
export const POSSIBLE_THRESHOLD = 0.62;

/** Incident types that can describe the same underlying event. */
const COMPATIBLE: Record<string, string[]> = {
  flood_entrapment: ["flood_entrapment", "flood_damage", "blocked_access", "medical_emergency"],
  flood_damage: ["flood_damage", "flood_entrapment", "blocked_access"],
  blocked_access: ["blocked_access", "flood_damage", "flood_entrapment"],
  medical_emergency: ["medical_emergency", "flood_entrapment"],
  other: ["other"],
};

export function haversineMetres(
  a: { lat: number; lon: number },
  b: { lat: number; lon: number },
): number {
  const dLat = (b.lat - a.lat) * M_PER_DEG;
  const dLon = (b.lon - a.lon) * M_PER_DEG * Math.cos((a.lat * Math.PI) / 180);
  return Math.sqrt(dLat * dLat + dLon * dLon);
}

export function cosine(a: number[], b: number[]): number {
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  return na && nb ? dot / (Math.sqrt(na) * Math.sqrt(nb)) : 0;
}

/** The text used for similarity: what happened, not who reported it. */
export function similarityText(e: Extraction): string {
  return [
    e.incident_type,
    e.english_summary,
    e.urgency_indicators.join(" "),
    e.locations_mentioned.join(" "),
    e.road_access,
  ]
    .filter(Boolean)
    .join(" | ");
}

export async function embed(
  texts: string[],
  apiKey = process.env.DASHSCOPE_API_KEY,
): Promise<number[][] | null> {
  if (!apiKey || texts.length === 0) return null;
  try {
    const res = await fetch(`${BASE}/embeddings`, {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model: EMBED_MODEL, input: texts }),
    });
    if (!res.ok) return null;
    const j = await res.json();
    const out = (j.data ?? [])
      .sort((a: { index: number }, b: { index: number }) => a.index - b.index)
      .map((d: { embedding: number[] }) => d.embedding);
    return out.length === texts.length ? out : null;
  } catch {
    return null;
  }
}

/**
 * Token-overlap fallback for when the embedding endpoint is unavailable. Weaker than
 * embeddings, so it is deliberately only allowed to produce "possible duplicate",
 * never an automatic link: degraded matching must not silently merge incidents.
 */
export function lexicalSimilarity(a: string, b: string): number {
  const norm = (s: string) =>
    new Set(
      s.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, " ").split(/\s+/).filter((w) => w.length > 2),
    );
  const A = norm(a), B = norm(b);
  if (!A.size || !B.size) return 0;
  let shared = 0;
  for (const w of A) if (B.has(w)) shared++;
  return shared / Math.min(A.size, B.size);
}

export type Candidate = {
  incident: IncidentRow;
  similarity: number;
  /** null when either side has no coordinates: proximity could not be checked. */
  distanceM: number | null;
  ageMs: number;
  method: "embedding" | "lexical";
  /** True only when both sides had coordinates and passed the radius gate. */
  geoConfirmed: boolean;
};

export type LinkDecision =
  | { action: "link"; incidentId: string; candidate: Candidate }
  | { action: "possible"; candidates: Candidate[] }
  | { action: "new"; candidates: Candidate[] };

type IncidentWithText = IncidentRow & { sim_text: string | null };

/**
 * Candidate gate: an existing incident only competes if it is close in time, of a
 * compatible type, and (when both have coordinates) within the geo radius. Reports
 * without coordinates are not excluded, since a citizen may not share location;
 * they simply lean harder on text similarity.
 */
function candidateIncidents(e: Extraction, lat: number | null, lon: number | null): IncidentWithText[] {
  const since = Date.now() - TIME_WINDOW_MS;
  const compatible = COMPATIBLE[e.incident_type] ?? [e.incident_type];
  const placeholders = compatible.map(() => "?").join(",");

  const rows = db()
    .prepare(
      `SELECT i.*, (
         SELECT r.extraction_json FROM reports r
         WHERE r.incident_id = i.id AND r.extraction_json IS NOT NULL
         ORDER BY r.created_at ASC LIMIT 1
       ) AS first_extraction
       FROM incidents i
       WHERE i.created_at >= ? AND i.status != 'resolved' AND i.incident_type IN (${placeholders})
       ORDER BY i.created_at DESC LIMIT 50`,
    )
    .all(since, ...compatible) as (IncidentRow & { first_extraction: string | null })[];

  return rows
    .filter((r) => {
      if (lat === null || lon === null || r.lat === null || r.lon === null) return true;
      return haversineMetres({ lat, lon }, { lat: r.lat, lon: r.lon }) <= GEO_RADIUS_M;
    })
    .map((r) => ({
      ...r,
      sim_text: r.first_extraction
        ? similarityText(JSON.parse(r.first_extraction) as Extraction)
        : r.summary,
    }));
}

export async function findDuplicate(
  e: Extraction,
  lat: number | null,
  lon: number | null,
): Promise<LinkDecision> {
  const pool = candidateIncidents(e, lat, lon);
  if (pool.length === 0) return { action: "new", candidates: [] };

  const mine = similarityText(e);
  const theirs = pool.map((p) => p.sim_text ?? "");

  const vectors = await embed([mine, ...theirs]);
  let method: Candidate["method"] = "embedding";
  let scores: number[];

  if (vectors) {
    const [self, ...rest] = vectors;
    scores = rest.map((v) => cosine(self, v));
  } else {
    method = "lexical";
    scores = theirs.map((t) => lexicalSimilarity(mine, t));
  }

  const candidates: Candidate[] = pool
    .map((p, i) => {
      const geoKnown =
        lat !== null && lon !== null && p.lat !== null && p.lon !== null;
      return {
        incident: p,
        similarity: Number(scores[i].toFixed(4)),
        distanceM: geoKnown
          ? Math.round(haversineMetres({ lat, lon }, { lat: p.lat!, lon: p.lon! }))
          : null,
        ageMs: Date.now() - p.created_at,
        method,
        geoConfirmed: geoKnown,
      };
    })
    .sort((a, b) => b.similarity - a.similarity);

  const best = candidates[0];

  // Auto-linking requires BOTH strong embedding similarity AND confirmed proximity.
  //
  // Measured 2026-08-28: two reports with identical wording describing genuinely
  // different households 13.5km apart score 0.851, above the auto-link threshold.
  // Text similarity alone therefore cannot be trusted to merge, because a wrong
  // merge hides an emergency and the family in the second house is never reached.
  // Without coordinates on both sides the match can only ever be proposed.
  if (
    method === "embedding" &&
    best.geoConfirmed &&
    best.similarity >= AUTO_LINK_THRESHOLD
  ) {
    return { action: "link", incidentId: best.incident.id, candidate: best };
  }
  if (best.similarity >= POSSIBLE_THRESHOLD) {
    return { action: "possible", candidates: candidates.slice(0, 3) };
  }
  return { action: "new", candidates: candidates.slice(0, 3) };
}
