"""
Draw the AmanSignal logo: the mark, plus the wordmark as outlines.

The wordmark is Fraunces 700 converted to paths rather than set as live text,
for one reason that matters more than fidelity: the logo has to be the same
object in the app, in a PDF, in a video frame and in a link preview. Live text
is only the same object where the same font is loaded, and the app deliberately
does not load a display face, because it is built for bad connections and a
wordmark is not worth a font request. Outlines cost nothing at runtime and
cannot be substituted.

Run this only when the logotype itself changes, which should be never. It needs
fontTools and a Fraunces 700 TTF, passed as the first argument:

    python tools/make-logo.py path/to/Fraunces-700.ttf

Writes public/logo.svg, public/logo-stacked.svg and app/logo-path.ts. The
generated files are committed, so the build never depends on this script.
"""

import sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.misc.transform import Transform

WORD = "AmanSignal"

# The mark, in its own 48-unit square. Kept identical to app/Mark.tsx, which is
# also what the favicon and the installed app icon are cut from.
MARK_INNER = (
    '<g fill="none" stroke="currentColor" stroke-width="3.4" stroke-linecap="round">'
    '<path d="M11.5 25.5a17 17 0 0 1 25 0"/>'
    '<path d="M17 31.5a9.5 9.5 0 0 1 14 0"/>'
    '<path d="M5 41h38"/>'
    '<path d="M5 45.5h38" opacity=".42"/></g>'
    '<circle cx="24" cy="36.5" r="2.9" fill="currentColor"/>'
)
# The mark's ink box inside that square: the stroke extends past the geometry,
# so the drawn extent is wider and lower than the path coordinates suggest.
MARK_BOX = (3.3, 18.33, 41.4, 28.87)  # x, y, w, h

MARK_H = 1.22   # mark ink height, as a multiple of the wordmark's cap height
GAP = 0.48      # space between mark and word, same units
STACK_GAP = 0.42
STACK_MARK = 2.3   # the stacked mark carries a cover, so it is sized to hold one


def wordmark(font_path):
    f = TTFont(font_path)
    cmap, gs, hmtx = f.getBestCmap(), f.getGlyphSet(), f["hmtx"]
    names = [cmap[ord(c)] for c in WORD]
    parts, x, bounds = [], 0, BoundsPen(gs)
    for g in names:
        # y is flipped into SVG space, leaving the baseline at y=0.
        t = Transform(1, 0, 0, -1, x, 0)
        pen = SVGPathPen(gs)
        gs[g].draw(TransformPen(pen, t))
        if pen.getCommands():
            parts.append(pen.getCommands())
        gs[g].draw(TransformPen(bounds, t))
        x += hmtx[g][0]
    return " ".join(parts), bounds.bounds, f["OS/2"].sCapHeight


def place(cap, wx0, wx1):
    """Mark transform and word offset for the horizontal lockup."""
    h = cap * MARK_H
    s = h / MARK_BOX[3]
    w = MARK_BOX[2] * s
    top = -cap + (cap - h) / 2          # centred on the cap-height band
    return s, w, (-MARK_BOX[0] * s, top - MARK_BOX[1] * s), w + cap * GAP - wx0


def svg(view, body):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}" fill="none">'
        f'<title>AmanSignal</title>{body}</svg>\n'
    )


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    path, (wx0, wy0, wx1, wy1), cap = wordmark(sys.argv[1])
    s, mw, (tx, ty), wx = place(cap, wx0, wx1)
    mtop, mh = -cap + (cap - cap * MARK_H) / 2, cap * MARK_H

    g = lambda t, sc: f'<g transform="translate({t[0]:.1f} {t[1]:.1f}) scale({sc:.5f})">{MARK_INNER}</g>'
    word = lambda dx, dy=0: (
        f'<path transform="translate({dx:.1f} {dy:.1f})" d="{path}" fill="currentColor"/>'
    )

    # Horizontal.
    y0, y1 = min(mtop, wy0), max(mtop + mh, wy1)
    w = mw + cap * GAP + (wx1 - wx0)
    open("public/logo.svg", "w", encoding="utf-8").write(
        svg(f"0 {y0:.0f} {w:.0f} {y1 - y0:.0f}", g((tx, ty), s) + word(wx))
    )

    # Stacked: the mark centred over the word, for square and cover contexts.
    sh = cap * STACK_MARK
    ss = sh / MARK_BOX[3]
    sw, ww = MARK_BOX[2] * ss, wx1 - wx0
    total = max(sw, ww)
    mx, wx2 = (total - sw) / 2 - MARK_BOX[0] * ss, (total - ww) / 2 - wx0
    my = -cap - cap * STACK_GAP - sh - MARK_BOX[1] * ss
    top = -cap - cap * STACK_GAP - sh
    open("public/logo-stacked.svg", "w", encoding="utf-8").write(
        svg(f"0 {top:.0f} {total:.0f} {wy1 - top:.0f}", g((mx, my), ss) + word(wx2))
    )

    # The same geometry for the app, so React renders the identical object.
    ts = f"""/**
 * Generated by tools/make-logo.py. Do not edit by hand.
 *
 * The wordmark as outlines, in font units with the baseline at y=0, plus the
 * numbers app/Logo.tsx needs to place the mark against it.
 */
export const WORDMARK = "{path}";
export const METRICS = {{
  cap: {cap},
  word: {{ x0: {wx0:.0f}, y0: {wy0:.0f}, x1: {wx1:.0f}, y1: {wy1:.0f} }},
  mark: {{ scale: {s:.5f}, x: {tx:.1f}, y: {ty:.1f}, w: {mw:.1f} }},
  wordX: {wx:.1f},
  view: {{ y: {y0:.0f}, w: {w:.0f}, h: {y1 - y0:.0f} }},
}};
"""
    open("app/logo-path.ts", "w", encoding="utf-8").write(ts)
    for p in ("public/logo.svg", "public/logo-stacked.svg", "app/logo-path.ts"):
        print("wrote", p)


main()
